name: Build

on:
  push:
    branches: ["main"]
    paths-ignore:
      - '**/*.md'
      - '**/.gitignore'
      - '**/LICENSE'
      - '**/PKGBUILD'
      - '**/.editorconfig'
    tags:
      - 'v*'

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
        contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Build distributions
        run: |
          pip install build
          python -m build

      - name: Generate SHA256SUMS
        run: |
          cd dist
          sha256sum * > SHA256SUMS

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: animein-dist
          path: dist/

  release_nightly:
    needs: build
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: animein-dist
          path: dist

      - name: Rename and Update Checksum
        run: |
          cd dist
          rm -f SHA256SUMS
          mv *.whl yt_dlp_animein_latest.whl
          mv *.tar.gz yt_dlp_animein_latest.tar.gz
          sha256sum * > SHA256SUMS

      - name: Create Nightly Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: Latest Build
          prerelease: true
          make_latest: false
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: animein-dist
          path: dist

      - name: Create Versioned Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
